spring:
  config:
    import: "optional:file:config/.env[.properties]"

  application:
    name: config
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8888