spring:
  application:
    name: order
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  cloud:
    loadbalancer:
      eager-load:
        clients: product

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true