server:
  port: 9999

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product
              uri: lb://PRODUCT
              predicates:
                - Path=/api/v1/products,/api/v1/products/**

            - id: user
              uri: lb://USER
              predicates:
                - Path=/api/v1/users,/api/v1/users/**

            - id: order
              uri: lb://ORDER
              predicates:
                - Path=/api/v1/order,/api/v1/order/**,/api/v1/cart,/api/v1/cart/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE