server:
  port: 8881

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/codey/Desktop/my-apps/Spring_Ecommerce_App/additional/config-management/configserver/src/main/resources/shared/config

## Set active profile to jdbc to fetch configuration from a database
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:postgresql://localhost:5432/config_db
#    username: codey
#    password: admin
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
##  Fetch configuration from a database
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION = ? and PROFILE = ? and LABEL = ?;"
#          default-label: main

## Fetch configuration dynamically directly from a private GitHub repository using git
#  cloud:
#    config:
#      server:
#        git:
#          uri: ${GITHUB_URI}
#          privateKey: ${GITHUB_PRIVATE_KEY_PATH}
#          clone-on-start: true
#          default-label: main
#          skip-ssl-validation: false
#          timeout: 10

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Encrypt the configuration using AES encryption
#encrypt:
#  key: "0EW12EA6YUIATRUVONIN"

# Encrypt the configuration using a key store
encrypt:
  key-store:
    location: ${KEY_STORE_PATH}
    password: ${KEY_STORE_PASSWORD}
    alias: ${KEY_STORE_ALIAS}
