server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/config

management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  info:
    env:
      enabled: true