spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm_db
    username: codey
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8883

info:
  app:
    name: product
    description: Product service for ecommerce app
    version: 1.0.0
