build:
  id: 1
  version: 1.0.0
  name: "{cipher}AQBoq1b87Knjvl61iDJkNwvQfZ34h8W9fKZCe3SwbB1UDjCMH2ZLUuPtlcBFHLaQjY+2DZpHKKzu4dMi346IFRz4TWf/tsn/K61qdqPW4j/QU5SX9TgPXzBdalkY0XKfoZVkd0TezjAl488TBYVXDnGo7alwKc5qoolPfeadeC4ySN5gp504Pd/3/fs9oqcbpMbAzSJDw40VXXgVPosUpbejb8zAjLmrkWvFjEWhdA5y7u2iU0nHFOf4cUY4grvep0q6rBhPJPOHu/3JusCYjQA0s8nWbkt8LtZSQ3z44KwDo+g+JsUXlOHOah/ugBxPkKkmJL3vcYYDm36tyoXJd63MGOtcTKsw8SUgF3mJ6Y0U12iIYM3fkz1PEe23RWut7fJtFxpVKiHPxFlo1iTKYAEz"
  type: "Updated Git-Configuration"